### ISSUE TITLE
Not working when rebooting PC?

### ISSUE THREAD

**Issue by victor-marino** [MeisApps/pcbu-natives#3]
Hey there!

I'm trying your nice little app as a method to unlock a living room PC without having to use a keyboard.

From what I've seen so far, it seems to work great when my PC is locked after having previously unlocked it with a different method already.

However, if I completely restart my PC, the prompt never pops up in my phone, and hovering my mouse over the unlock method in the lock screen shows a tooltip with the message `Could not connect to phone`.

Is this the expected behaviour? Or should the app also work when unlocking the PC for the first time after boot?

**Comment by MeisApps** [comment]
Is your PC using Wi-Fi? If so, the connections fails because the Wi-Fi connection might not be established yet when you try to unlock.
