### ISSUE TITLE
How does the WearOS unlock work (Pro feature)? Is it based on regular notification buttons?

### ISSUE THREAD

**Issue by victor-marino** [MeisApps/pcbu-natives#4]
I see there's a Pro option to unlock the device with Wear OS devices. How does this work exactly? Is it just a regular notification with an integrated button to approve the request?

I don't have a Wear OS device myself, but I do have a Garmin watch that also allows you to "click" on any buttons shown by the notification. This would be exactly what I'm looking for, so it'd be a instant buy for me :)

(Also, if that's the case you should probably clarify it in the description, as it wouldn't really be a WearOS exclusive feature!)

**Comment by julianullrich99** [comment]
I have the same question. I purchased pro for this but can't enable the option..

**Comment by MeisApps** [comment]
The notification uses Wearable Extender (https://developer.android.com/reference/android/app/Notification.WearableExtender) to show the buttons to the user. I only tested this with a Wear OS watch, however it should also work with other smartwatches.

@julianullrich99 Please try restarting the app by force quitting it in the apps section in settings. If that doesn't help, try restarting your phone or reinstalling the app. Are the other pro settings locked as well? Did the app restart after you bought it? Seems like a bug where the app does not register the purchase fully. I tried reproducing the bug on my device, but there it's working fine.

**Comment by julianullrich99** [comment]
Thanks for your reply!
The issue was bio encryption. It works now.

However: it would be cool to show a fullscreen button-screen, not a notification.
I have a WearOs Watch, but it just shows me the notification, which takes some time to expand.

Is there any plan to improve this?

I just really love your app since I discovered it yesterday. Greetings from germany!

**Comment by MeisApps** [comment]
@julianullrich99 Ah, the only thing I did not think about...
Glad you like it! Which watch are you using exactly? On my Galaxy Watch 4 and the Watch OS emulator, the buttons are shown immediately.

Grüße aus Hessen ;)
